In [ ]:
import pandas as pd
import numpy as np

### TIME SERIES ANALYSIS

In [ ]:
df_sales = pd.read_csv('sales_data.csv')
df_sales

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [ ]:
df_sales['Sale_Date']

0      2023-02-03
1      2023-04-21
2      2023-09-21
3      2023-08-24
4      2023-03-24
          ...
995    2023-04-15
996    2023-09-07
997    2023-04-27
998    2023-12-20
999    2023-08-16
Name: Sale_Date, Length: 1000, dtype: object

In [ ]:
df_sales['Sale_Date'] = pd.to_datetime(df_sales['Sale_Date'] , format='%Y-%m-%d')
df_sales['Sale_Date']

0     2023-02-03
1     2023-04-21
2     2023-09-21
3     2023-08-24
4     2023-03-24
         ...
995   2023-04-15
996   2023-09-07
997   2023-04-27
998   2023-12-20
999   2023-08-16
Name: Sale_Date, Length: 1000, dtype: datetime64[ns]

In [ ]:
df_sales.set_index('Sale_Date', inplace=True)
df_sales

,Product_ID,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
Sale_Date,,,,,,,,,,,,,
2023-02-03,1052,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
2023-04-21,1093,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2023-09-21,1015,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
2023-08-24,1072,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
2023-03-24,1061,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-15,1010,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
2023-09-07,1067,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
2023-04-27,1018,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
2023-12-20,1100,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
2023-08-16,1086,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [ ]:
df_sales.sort_index(inplace=True)
df_sales

,Product_ID,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
Sale_Date,,,,,,,,,,,,,
2023-01-01,1070,Eve,South,783.18,12,Furniture,664.33,863.03,Returning,0.25,Bank Transfer,Retail,South-Eve
2023-01-01,1089,Charlie,North,8130.13,35,Clothing,4071.01,4304.70,New,0.14,Credit Card,Online,North-Charlie
2023-01-01,1008,Eve,North,5227.81,38,Clothing,4635.23,5075.44,Returning,0.05,Cash,Online,North-Eve
2023-01-02,1064,David,South,5533.70,10,Electronics,2242.01,2282.23,Returning,0.20,Credit Card,Online,South-David
2023-01-02,1075,David,West,919.09,26,Electronics,4535.38,4557.56,New,0.00,Credit Card,Online,West-David
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31,1090,Eve,West,3333.73,46,Clothing,4665.12,4675.90,New,0.19,Cash,Retail,West-Eve
2023-12-31,1094,Bob,South,6586.22,15,Food,4111.93,4338.67,Returning,0.26,Credit Card,Online,South-Bob
2024-01-01,1018,Alice,West,8579.72,24,Electronics,1362.78,1729.81,New,0.29,Bank Transfer,Online,West-Alice
2024-01-01,1098,Bob,South,2370.72,11,Clothing,213.41,503.36,Returning,0.27,Bank Transfer,Online,South-Bob
2024-01-01,1078,David,East,8377.57,42,Food,63.41,314.93,Returning,0.03,Cash,Retail,East-David

In [ ]:
df_sales.loc['2023-01-01']

,Product_ID,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
Sale_Date,,,,,,,,,,,,,
2023-01-01,1070,Eve,South,783.18,12,Furniture,664.33,863.03,Returning,0.25,Bank Transfer,Retail,South-Eve
2023-01-01,1089,Charlie,North,8130.13,35,Clothing,4071.01,4304.70,New,0.14,Credit Card,Online,North-Charlie
2023-01-01,1008,Eve,North,5227.81,38,Clothing,4635.23,5075.44,Returning,0.05,Cash,Online,North-Eve

In [ ]:
df_sales.loc['2023-01-01':'2024-01-02':2]

,Product_ID,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
Sale_Date,,,,,,,,,,,,,
2023-01-01,1070,Eve,South,783.18,12,Furniture,664.33,863.03,Returning,0.25,Bank Transfer,Retail,South-Eve
2023-01-01,1008,Eve,North,5227.81,38,Clothing,4635.23,5075.44,Returning,0.05,Cash,Online,North-Eve
2023-01-02,1075,David,West,919.09,26,Electronics,4535.38,4557.56,New,0.00,Credit Card,Online,West-David
2023-01-03,1099,Bob,East,5613.10,31,Furniture,4632.85,4711.70,New,0.21,Cash,Retail,East-Bob
2023-01-04,1074,Eve,South,7508.72,38,Furniture,1394.74,1848.69,Returning,0.00,Bank Transfer,Retail,South-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-30,1003,Alice,East,640.88,17,Furniture,395.11,676.66,Returning,0.25,Cash,Retail,East-Alice
2023-12-31,1058,Alice,West,4643.51,44,Clothing,1910.47,2217.80,New,0.22,Bank Transfer,Online,West-Alice
2023-12-31,1003,Alice,South,4775.59,30,Furniture,4190.28,4270.65,New,0.20,Cash,Online,South-Alice
2023-12-31,1094,Bob,South,6586.22,15,Food,4111.93,4338.67,Returning,0.26,Credit Card,Online,South-Bob
2024-01-01,1098,Bob,South,2370.72,11,Clothing,213.41,503.36,Returning,0.27,Bank Transfer,Online,South-Bob

In [ ]:
df_sales.loc['2023-01']

,Product_ID,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
Sale_Date,,,,,,,,,,,,,
2023-01-01,1070,Eve,South,783.18,12,Furniture,664.33,863.03,Returning,0.25,Bank Transfer,Retail,South-Eve
2023-01-01,1089,Charlie,North,8130.13,35,Clothing,4071.01,4304.70,New,0.14,Credit Card,Online,North-Charlie
2023-01-01,1008,Eve,North,5227.81,38,Clothing,4635.23,5075.44,Returning,0.05,Cash,Online,North-Eve
2023-01-02,1064,David,South,5533.70,10,Electronics,2242.01,2282.23,Returning,0.20,Credit Card,Online,South-David
2023-01-02,1075,David,West,919.09,26,Electronics,4535.38,4557.56,New,0.00,Credit Card,Online,West-David
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-29,1092,Bob,South,8936.33,13,Clothing,2684.50,2913.78,New,0.08,Credit Card,Retail,South-Bob
2023-01-29,1007,Charlie,West,2491.21,13,Furniture,3765.46,3860.56,Returning,0.22,Cash,Retail,West-Charlie
2023-01-29,1017,Charlie,South,4882.09,19,Electronics,1233.12,1697.19,New,0.10,Credit Card,Online,South-Charlie
2023-01-31,1042,Alice,North,5207.03,11,Food,635.20,814.14,Returning,0.02,Cash,Online,North-Alice
2023-01-31,1057,Charlie,North,975.01,36,Food,4995.30,5165.09,Returning,0.24,Cash,Online,North-Charlie

In [ ]:
df_sales.loc['2023']

,Product_ID,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
Sale_Date,,,,,,,,,,,,,
2023-01-01,1070,Eve,South,783.18,12,Furniture,664.33,863.03,Returning,0.25,Bank Transfer,Retail,South-Eve
2023-01-01,1089,Charlie,North,8130.13,35,Clothing,4071.01,4304.70,New,0.14,Credit Card,Online,North-Charlie
2023-01-01,1008,Eve,North,5227.81,38,Clothing,4635.23,5075.44,Returning,0.05,Cash,Online,North-Eve
2023-01-02,1064,David,South,5533.70,10,Electronics,2242.01,2282.23,Returning,0.20,Credit Card,Online,South-David
2023-01-02,1075,David,West,919.09,26,Electronics,4535.38,4557.56,New,0.00,Credit Card,Online,West-David
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31,1058,Alice,West,4643.51,44,Clothing,1910.47,2217.80,New,0.22,Bank Transfer,Online,West-Alice
2023-12-31,1086,Alice,South,9269.32,33,Clothing,3419.33,3890.36,Returning,0.21,Cash,Retail,South-Alice
2023-12-31,1003,Alice,South,4775.59,30,Furniture,4190.28,4270.65,New,0.20,Cash,Online,South-Alice
2023-12-31,1090,Eve,West,3333.73,46,Clothing,4665.12,4675.90,New,0.19,Cash,Retail,West-Eve
2023-12-31,1094,Bob,South,6586.22,15,Food,4111.93,4338.67,Returning,0.26,Credit Card,Online,South-Bob

In [ ]:
df_sales.resample('ME')[['Sales_Amount','Discount']].sum()

            Sales_Amount  Discount
Sale_Date
2023-01-31     476092.36     14.38
2023-02-28     368919.36     11.80
2023-03-31     402638.77     11.91
2023-04-30     438992.61     13.58
2023-05-31     389078.76     11.06
2023-06-30     418458.34     13.32
2023-07-31     374242.88     10.45
2023-08-31     443171.28     13.39
2023-09-30     367837.60     11.22
2023-10-31     460378.78     13.17
2023-11-30     467482.90     14.80
2023-12-31     392643.58     12.72
2024-01-31      19328.01      0.59

In [ ]:
df_sales.resample('W')[['Sales_Amount','Discount']].sum()

            Sales_Amount  Discount
Sale_Date
2023-01-01      14141.12      0.44
2023-01-08     105431.80      3.65
2023-01-15     152631.59      3.82
2023-01-22      94289.63      2.46
2023-01-29     103416.18      3.75
2023-02-05      52467.98      2.10
2023-02-12     143365.78      4.82
2023-02-19      70226.00      1.91
2023-02-26      67897.55      1.89
2023-03-05     126241.63      3.85
2023-03-12      33668.94      1.16
2023-03-19     102998.58      3.08
2023-03-26      90160.69      2.95
2023-04-02     114804.29      3.29
2023-04-09      91813.20      3.72
2023-04-16     101290.93      2.75
2023-04-23     102246.65      2.83
2023-04-30     119550.56      3.20
2023-05-07      56622.67      1.83
2023-05-14     122068.78      3.39
2023-05-21      75253.95      1.90
2023-05-28     107965.46      2.84
2023-06-04     101105.82      3.90
2023-06-11      89025.70      3.45
2023-06-18      65394.10      2.13
2023-06-25      87026.12      2.84
2023-07-02     134883.37      2.96
2023-07-09      68709.85      1.41
2023-07-16      81441.00      2.40
2023-07-23     105341.52      3.13
2023-07-30      78850.80      2.58
2023-08-06     114175.81      2.91
2023-08-13      78864.23      3.26
2023-08-20     125928.27      3.12
2023-08-27      86677.68      2.80
2023-09-03      66201.06      2.18
2023-09-10      73055.47      1.67
2023-09-17      68057.64      1.87
2023-09-24     118229.53      4.09
2023-10-01      98930.70      3.01
2023-10-08      56915.46      1.27
2023-10-15     131656.99      3.66
2023-10-22     137823.36      4.23
2023-10-29      94875.48      3.17
2023-11-05     108944.14      3.01
2023-11-12     112326.60      3.44
2023-11-19     119254.40      3.93
2023-11-26     123104.95      4.10
2023-12-03      63018.35      2.10
2023-12-10      74485.56      1.97
2023-12-17      66461.84      2.40
2023-12-24      80186.96      2.79
2023-12-31     140430.50      4.39
2024-01-07      19328.01      0.59

In [ ]:
df_sales.resample('QE')[['Sales_Amount','Discount']].sum()

            Sales_Amount  Discount
Sale_Date
2023-03-31    1247650.49     38.09
2023-06-30    1246529.71     37.96
2023-09-30    1185251.76     35.06
2023-12-31    1320505.26     40.69
2024-03-31      19328.01      0.59

In [ ]:
df_sales.resample('YE')[['Sales_Amount','Discount']].sum()

            Sales_Amount  Discount
Sale_Date
2023-12-31    4999937.22    151.80
2024-12-31      19328.01      0.59

In [ ]:
df_sales.rolling(7)[['Sales_Amount','Discount']].sum()

            Sales_Amount  Discount
Sale_Date
2023-01-01           NaN       NaN
2023-01-01           NaN       NaN
2023-01-01           NaN       NaN
2023-01-02           NaN       NaN
2023-01-02           NaN       NaN
...                  ...       ...
2023-12-31      38680.06      1.46
2023-12-31      38464.57      1.46
2024-01-01      46403.41      1.50
2024-01-01      39558.81      1.64
2024-01-01      43292.87      1.45

[1000 rows x 2 columns]

In [ ]:
df_sales.rolling('7D')[['Sales_Amount','Discount']].sum()

            Sales_Amount  Discount
Sale_Date
2023-01-01        783.18      0.25
2023-01-01       8913.31      0.39
2023-01-01      14141.12      0.44
2023-01-02      19674.82      0.64
2023-01-02      20593.91      0.64
...                  ...       ...
2023-12-31     133844.28      4.13
2023-12-31     140430.50      4.39
2024-01-01     125708.82      4.03
2024-01-01     128079.54      4.30
2024-01-01     136457.11      4.33

[1000 rows x 2 columns]

In [ ]:
df = pd.DataFrame()

In [ ]:
df_sales.reset_index(inplace=True)
df_sales

,Sale_Date,Product_ID,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,2023-01-01,1070,Eve,South,783.18,12,Furniture,664.33,863.03,Returning,0.25,Bank Transfer,Retail,South-Eve
1,2023-01-01,1089,Charlie,North,8130.13,35,Clothing,4071.01,4304.70,New,0.14,Credit Card,Online,North-Charlie
2,2023-01-01,1008,Eve,North,5227.81,38,Clothing,4635.23,5075.44,Returning,0.05,Cash,Online,North-Eve
3,2023-01-02,1064,David,South,5533.70,10,Electronics,2242.01,2282.23,Returning,0.20,Credit Card,Online,South-David
4,2023-01-02,1075,David,West,919.09,26,Electronics,4535.38,4557.56,New,0.00,Credit Card,Online,West-David
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023-12-31,1090,Eve,West,3333.73,46,Clothing,4665.12,4675.90,New,0.19,Cash,Retail,West-Eve
996,2023-12-31,1094,Bob,South,6586.22,15,Food,4111.93,4338.67,Returning,0.26,Credit Card,Online,South-Bob
997,2024-01-01,1018,Alice,West,8579.72,24,Electronics,1362.78,1729.81,New,0.29,Bank Transfer,Online,West-Alice
998,2024-01-01,1098,Bob,South,2370.72,11,Clothing,213.41,503.36,Returning,0.27,Bank Transfer,Online,South-Bob
999,2024-01-01,1078,David,East,8377.57,42,Food,63.41,314.93,Returning,0.03,Cash,Retail,East-David

In [ ]:
df['Sale_Date'] = df_sales['Sale_Date']
df

     Sale_Date
0   2023-01-01
1   2023-01-01
2   2023-01-01
3   2023-01-02
4   2023-01-02
..         ...
995 2023-12-31
996 2023-12-31
997 2024-01-01
998 2024-01-01
999 2024-01-01

[1000 rows x 1 columns]

In [ ]:
df['Product_ID'] = df_sales['Product_ID']
df['Sales_Rep'] = df_sales['Sales_Rep']
df['Sales_Amount'] = df_sales['Sales_Amount']
df['Discount'] = df_sales['Discount']

In [ ]:
df.head()

   Sale_Date  Product_ID Sales_Rep  Sales_Amount  Discount
0 2023-01-01        1070       Eve        783.18      0.25
1 2023-01-01        1089   Charlie       8130.13      0.14
2 2023-01-01        1008       Eve       5227.81      0.05
3 2023-01-02        1064     David       5533.70      0.20
4 2023-01-02        1075     David        919.09      0.00

In [ ]:
df['day'] = df['Sale_Date'].dt.day
df['month'] = df['Sale_Date'].dt.month
df['year'] = df['Sale_Date'].dt.year
df['quarter'] = df['Sale_Date'].dt.quarter


df['weekday'] = df['Sale_Date'].dt.weekday
df['day_name'] = df['Sale_Date'].dt.day_name()
# df['dayofyear'] = df['Sale_Date'].dt.dayofyear
# df['is_month_start'] = df['Sale_Date'].dt.is_month_start
# df['is_month_end'] = df['Sale_Date'].dt.is_month_end
# df['is_quarter_start'] = df['Sale_Date'].dt.is_quarter_start
# df['is_quarter_end'] = df['Sale_Date'].dt.is_quarter_end
# df['is_year_start'] = df['Sale_Date'].dt.is_year_start
# df['is_year_end'] = df['Sale_Date'].dt.is_year_end
# df['is_leap_year'] = df['Sale_Date'].dt.is_leap_year
# df['days_in_month'] = df['Sale_Date'].dt.days_in_month

In [ ]:
df.head(5)

,Sale_Date,Product_ID,Sales_Rep,Sales_Amount,Discount,day,month,year,quarter,weekday,day_name
0,2023-01-01,1070,Eve,783.18,0.25,1,1,2023,1,6,Sunday
1,2023-01-01,1089,Charlie,8130.13,0.14,1,1,2023,1,6,Sunday
2,2023-01-01,1008,Eve,5227.81,0.05,1,1,2023,1,6,Sunday
3,2023-01-02,1064,David,5533.70,0.20,2,1,2023,1,0,Monday
4,2023-01-02,1075,David,919.09,0.00,2,1,2023,1,0,Monday

In [ ]:
df_sales['Sale_Date'].asfreq('W')

Series([], Freq: W-SUN, Name: Sale_Date, dtype: datetime64[ns])

In [ ]:
date_range = pd.date_range(start='2023-01-01', end='2023-12-31', freq='D')
date_range

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-12-22', '2023-12-23', '2023-12-24', '2023-12-25',
               '2023-12-26', '2023-12-27', '2023-12-28', '2023-12-29',
               '2023-12-30', '2023-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

In [ ]:
df_movies = pd.read_csv('imdb_movies.csv')
df_movies.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
df_movies['single_genre'] = df_movies['Genre'].str.split(',').str[0]
df_movies.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,single_genre
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",Drama
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",Crime
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444",Action
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000",Crime
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000",Crime